### ISSUE TITLE
安装启动失败

### ISSUE THREAD

**Issue by terryzhouke** [tumashu/emacs-helper#1]
使用 emacs 27.2 启动 eh-installer.el 文件出现错误

emacs -Q -l eh-install.el

error:
concat: Wrong type argument: stringp, nil

哪里出问题了

**Comment by tumashu** [comment]
我个人不建议你完全用我的配置，拷贝粘贴里面的有用片段倒是可以。

--

**Comment by terryzhouke** [comment]
是因为没有.emacs 文件吗？

**Comment by tumashu** [comment]
你用 emacs 打开 eh-installer.el 然后 eval-buffer 试试。
